name: Publish Python 🐍 source distribution to PyPI

on: push

jobs:
  build:
    name: Build source distribution 📦
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: python3 -m pip install build --user
      - name: Build a source tarball (sdist) only
        run: python3 -m build --sdist
      - name: Store the distribution package
        uses: actions/upload-artifact@v4
        with:
          name: python-package-sdist
          path: dist/

  publish-to-pypi:
    name: Publish Python 🐍 source distribution 📦 to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/<package-name>  # Replace <package-name> with your PyPI project name.
    permissions:
      id-token: write
    steps:
      - name: Download the sdist artifact
        uses: actions/download-artifact@v4
        with:
          name: python-package-sdist
          path: dist/
      - name: Publish source distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    name: Sign the Python 🐍 source distribution with Sigstore and create GitHub Release
    needs: publish-to-pypi
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Download the sdist artifact
        uses: actions/download-artifact@v4
        with:
          name: python-package-sdist
          path: dist/
      - name: Sign the sdist with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: |
            ./dist/*.tar.gz
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release create "$GITHUB_REF_NAME" --repo "$GITHUB_REPOSITORY" --notes ""
      - name: Upload artifact signatures to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload "$GITHUB_REF_NAME" dist/** --repo "$GITHUB_REPOSITORY"
