name: Python build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
          matrix:
            python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10' ]
            os: ['windows-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel cmake
        pip install scikit-build ninja
        python setup.py bdist_wheel
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: "hygese-${{ matrix.os }}-${{ matrix.python-version }}.whl"
        path: dist/*.whl

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Python wheels manylinux build
      uses: RalfG/python-wheels-manylinux-build@v0.3.3
      with:
        python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39 cp310-cp310'
        build-requirements: 'cmake scikit-build ninja'
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: "hygese-manylinux"
        path: dist/*.whl
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

  publish:
    runs-on: ubuntu-latest
    needs: ['build', 'build-linux']
    steps:
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

#https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/